# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2c3d36eb36632c2c69fd4eb980cee2ebf7ba3a21e0def0e6f62cec08de7b9ba8c55f38ca044452d991fb350b541d647caddfd3e1c2b8e3d1ba26d2e8aabb438

test:
  secret_key_base: 05bd61f338002f8b83d32c0673e9201ac3f5f947f7a1f87f0a0ba35e2daf4ae8d78ef42380003ff15a927f2689b510e4cf543eacb6b1ede77808679613109104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
